### ISSUE TITLE
Removal of systemd-networkd blocks the possibility to re-enable it

### ISSUE THREAD

**Issue by filcopetti** [varigit/meta-variscite-sdk-imx#5]
The removal of systemd-networkd doesn't allow a layer with higher priority to overwrite this modifications, see the [Tech FAQ](https://wiki.yoctoproject.org/wiki/Technical_FAQ) below:

> How do I remove a value from a list variable?
> For variables that are expected to contain a space-separated list of items, BitBake supports a :remove operator to remove items from it. See [Removal (override style syntax)](http://www.yoctoproject.org/docs/current/bitbake-user-manual/bitbake-user-manual.html#removing-override-style-syntax) in the BitBake user manual.
> 
> NOTE: the :remove operation is final - you cannot "undo" it with other operations elsewhere, thus **you should really only make use of it in your distro / local configuration and not in layers that you expect others to re-use** for different purposes (and therefore they may need to undo your changes). An alternative way to effectively remove an item is to set the list outright to include all the items minus the one you want to remove.

Would it be possible to manage this differently in order to be able to overwrite the modification from a higher priority layer?

**Comment by filcopetti** [comment]
It should be possible to fix this miss-behavior by overwriting completely the variable:
PACKAGECONFIG-TEMP := "${PACKAGECONFIG}"
PACKAGECONFIG-TEMP:remove = "networkd"
PACKAGECONFIG := "${PACKAGECONFIG-TEMP}"

In this way, an :append of variable in another layer allow the re-enablement of systemd-networkd.

**Comment by filcopetti** [comment]
@dorta Do you see the possibility to integrate this change?

**Comment by nsdrude** [comment]
@filcopetti we will consider addressing this in a future release. Thank you for your feedback.

**Comment by varigigi** [comment]
@filcopetti, being the discussion moved to the customer portal, I'm now closing this issue.
Thanks
Best Regards
Pier
